import './globals.css'
import { ReduxProviders } from './ReduxProviders'
import ThemeProviders from './ThemeProviders'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProviders>
          <ReduxProviders>
            {children}
          </ReduxProviders>
        </ThemeProviders>
      </body>
    </html>
  )
}
